/************************************************************************************** 
 Apex Class Name     : ITPAServiceIntegrationInterface
 Version             : 1.0 
 Created Date        : 1st March 2016
 Function            : Interface class for ITPA Call
*************************************************************************************/
                    
public interface ITPAServiceIntegrationInterface {

    ITPAServiceInfoBean handleServiceRequest(ITPAServiceInfoBean serviceInfobean);
}