/************************************************************************************** 
 Apex Class Name     : SpecialCharacterBuyflowConstant
 Version             : 1.0 
 Created Date        :  8/13/2016
 Function            : This class tracks the constants
 Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Radhika Dhanapal          8/13/2016              Original Version
*************************************************************************************/
public with sharing class  SpecialCharacterBuyflowConstant {
public static final String ADD='+';
public static final String AMPERSAND='&';
public static final String ASC_CAPS_LITERAL='asc';
public static final String BACK_SLASH='\'';
public static final String BACK_SLASHTWO_SLASH='\\/';
public static final String BACKSLASH='\\';
public static final String BLANK_COMMA=' ,';
public static final String BLANK=' ';
public static final String BLANK1='  ';
public static final String BRACKETS='()';
public static final String CARET='^';
public static final String CLOSE_BRACKET=')';
public static final String CLOSE_SQUARE_BRACKETS=']]>';
public static final String CLOSEBRACKET=')';
public static final String CLOSED_BRACE=') ';
public static final String CLOSEFLOWERBRACKET='}';
public static final String COLEN=':';
public static final String COLON=':';
public static final String COMASPACE=', ';
public static final String COMMA_BACK_SLASH=', \'';
public static final String COMMA_SPACE=', ';
public static final String COMMA=',';
public static final String CONCAT='';
public static final String CONTINUE_CAPS_LITERAL='Continue';
public static final String DELETE_CAPS_LITERAL='Delete';
public static final String DESC_CAPS_LITERAL='desc';
public static final String DOLLARSPACE='$ ';
public static final String DOT_DOLLAR_ESCPAED='\\.$';
public static final String DOT='.';
public static final String DOUBLE_QOUTE='"';
public static final String DOUBLEDASH='--';
public static final String DOUBLESLASH_DOT='\\.';
public static final String DOUBLESPACE='  ';
public static final String EQUAL='=';
public static final String EQUALS_BACK_SLASH=' = \'';
public static final String FALSE_CAMEL_LITERAL='False';
public static final String FALSE_LITERAL='false';
public static final String GRETERTHAN='>';
public static final String HASH='#';
public static final String HYPHEN='-';
public static final String HYPHENDOLLARSPACE='-$ ';
public static final String INVERTED_COMMA='"  ';
public static final String LESSTHATN='<';
public static final String NEW_CAPS_LITERAL='New';
public static final String OPEN_BRACE='(';
public static final String OPENFLOWERBRACKET='{';
public static final String PERCENT='%';
public static final String PERCENTSPACEPIPESPACE='% | ';
public static final String QUESTIONMARK='?';
public static final String SELECT_CAPS_LITERAL='Select';
public static final String SEMICOLEN=';';
public static final String SEMICOLON_SPACE='; ';
public static final String SEMICOLON=';';
public static final String SINGLE_SPACE='  ';
public static final String SLASH='/';
public static final String SPACE_CLOSE_BRACKET=' )';
public static final String SPACECOLONSPACE=' : ';
public static final String SPACESLASHSPACE=' / ';
public static final String STAR='*';
public static final String STATIC_CAMEL_LITERAL='Static';
public static final String TAB_SPACE='   ';
public static final String TIDAL='~~';
public static final String TIDE='~';
public static final String TRUE_CAMEL_LITERAL='True';
public static final String TRUE_LITERAL='true';
public static final String UNDERSCORE='_';
public static final String TRUE_CAPS_LITERAL ='TRUE';
public static final String DOLLERSPACE='$ ';
}