/************************************************************************************** 
 Apex Class Name     : ASEITPAServiceIntegrationInterface
 Version             : 1.0 
 Created Date        : 9 November 2016
 Function            : Interface class for ASE ITPA Call
*************************************************************************************/
                    
public interface ASEITPAServiceIntegrationInterface{

    ASEITPAServiceInfoBean handleServiceRequest(ASEITPAServiceInfoBean serviceInfobean);
}