/************************************************************************************** 
 Apex Class Name     : ATTServiceInfoBean
 Version             : 1.0 
 Created Date        : 9 November 2016
 Function            : This class tracks the state of ASE ITPA Service Information
*************************************************************************************/
public with sharing abstract class ASEITPAServiceInfoBean{
  
  public string status;

}