/************************************************************************************** 
 Apex Class Name     : ATTServiceInfoBean
 Version             : 1.0 
 Created Date        : 11 Aug 2014
 Function            : This class tracks the state of service info
 Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Gustavo Restrepo            8/11/2014              Original Version
*************************************************************************************/
public with sharing abstract class ATTServiceInfoBean {
  
  public string status;

}