/************************************************************************************** 
Apex Class Name     : BlackFlagRequestBean
Version             : 1.0 
Created Date        : 17 Jan 2017
Function            : BlackFlag Request bean
*************************************************************************************/
public class BlackFlagRequestBean {
    


       public String access_token;
       public String token_type;
       public String expires_in;
       public String refresh_token;
       
       
}