public with sharing class CustomerConstant{
    
    public static final string UPLOAD_CSV_FILE = 'Please upload a csv file.';
    public static final string TEMPLATE_NAME = 'SiteAddressUploadTemplate_New';
    public static final string SITE_ALREADY_EXISTS = 'The site address already exists.';
    public static final string DUPLICATE_ADDRESS_FOUND = 'Duplicate Address Found. Please add a customer with new address';
    public static final string CORRECT_TEMPLATE_TEXT = 'Please upload the correct template.';
    public static final string SITE_DELETED = 'The site has been successfully deleted';
    public static final string MANDATORY_FIELDS_TEXT = 'Enter all the mandatory fields';
    public static final string MANDATORY_FIELDS_SAVE = 'Enter all mandatory fields to save the site';
    public static final string INVALID_FILE = 'Invalid File';
    public static final string NOTHING_TO_PROCESS = 'Nothing to Process';
    public static final string ENTER_SITE_ADDRESS = 'Enter a site address.';
    public static final string END_CUSTOMER_EXISTS =  'The End Customer Already Exists For This SP Account';
    
    public CustomerConstant(){
    	//Blank Constructor
    }
}