/************************************************************************************************
 Apex Class Name     : EsignContractInfoBean
 Version             : 1.0 
 Created Date        : 5 January 2017
 Function            : This class tracks the state of the Esign Request Calls
*************************************************************************************************/
public with sharing abstract class EsignContractInfoBean{
  
  public string status;

}