/************************************************************************************** 
 Apex Class Name     : ITPAServiceInfoBean 
 Version             : 1.0 
 Created Date        : 1st March 2016
 Function            : Class that tracks the state of the ITPA service information 
*************************************************************************************/

public with sharing abstract class ITPAServiceInfoBean {
  
  public string status;

}