/************************************************************************************** 
 Apex Class Name     : SpecialCharacterConstant
 Version             : 1.0 
 Created Date        :  9/01/2016
 Function            : This class tracks the Special Character constants
 Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Venkat Prabhjot Sahu          9/01/2016              Original Version
*************************************************************************************/
public with sharing class  SpecialCharacterConstant {
	        
	public static final String ADD='+';
	public static final String ASC_CAPS_LITERAL='asc';
	public static final String BACK_SLASH='\'';
	public static final String BACK_SLASH2_CLOSE_BRACKET='\\)';
	public static final String BACK_SLASHTWO_SLASH='\\/';
	public static final String BACKSLASH='\'';
	public static final String BACKSLASH2_OPEN_BRACKET='\\(';
	public static final String BRACKETS='()';
	public static final String CARET='^';
	public static final String CLOSE_BRACE_COMMA='},';
	public static final String CLOSE_BRACKET_COMMA_SPACE='],';
	public static final String CLOSE_BRACKET_SPACE=') ';
	public static final String CLOSE_BRACKET=')';
	public static final String CLOSE_SQUARE_BRACKETS=']]>';
	public static final String COLEN=':';
	public static final String COLENSPACE=': ';
	public static final String COMASPACE=', ';
	public static final String COMMA_BACK_SLASH=', \'';
	public static final String CONTINUE_CAPS_LITERAL='Continue';
	public static final String CURLYBRACKETS='{}';
	public static final String DELETE_CAPS_LITERAL='Delete';
	public static final String DESC_CAPS_LITERAL='desc';
	public static final String DOLLAR='$$$$$$$';
	public static final String EQUALS_BACK_SLASH=' = \'';
	public static final String EQUALS='=';
	public static final String FALSE_CAPS_LITERAL='FALSE';
	public static final String GRETERTHAN='>';
	public static final String GRETERTHANEQUAL='>=';
	public static final String LESSTHANEQUAL='<=';
	public static final String LESSTHATN='<';
	public static final String NEW_CAPS_LITERAL='New';
	public static final String NOTBRACES='!{}';
	public static final String ONLY_SLASH='/';
	public static final String OPENSQUAREBRACKET='[';
	public static final String PERCENT_PIPE='% | ';
	public static final String PERCENT='%';
	public static final String PIPESPACE='|';
	public static final String PLUS='+';
	public static final String QUESTIONMARK='?';
	public static final String SELECT_CAPS_LITERAL='Select';
	public static final String SEMICOLEN=';';
	public static final String SEMICOLON_SPACE='; ';
	public static final String SEMICOLON=';';
	public static final String SINGLE_SPACE='  ';
	public static final String SPACE_CLOSE_BRACE_COMMA=' },';
	public static final String SPACE_CLOSE_BRACKET=' )';
	public static final String SPACEHYPHENSPACE=' - ';
	public static final String SPACEPLUSSPACE=' + ';
	public static final String SPACESLASHSPACE=' / ';
	public static final String STAR='*';
	public static final String TAB_SPACE='   ';
	public static final String THREEDOTS='...';
	public static final String TIDAL='~~';
	public static final String TIDE='~';
	public static final String TWOBACKSPACECARET='\\^';
	public static final String TWOBACKSPACELINE='\\|';
	public static final String CLOSE_SQ_BRACE=']';
	public static final String OPEN_SQUARE_BRACKET='[';
	public static final String PERCENTAGE_OPENBRACKET='%(';
	public static final String QUESTION_MARK='?';
	public static final String SPACE_HYPHEN_SPACE=' - ';
	public static final String SPACE_OPENBRACKET_PERCENTAGE=' (%';
	public static final String SPACE_PERCENTAGE=' %';
	public static final String SPACE_QUESTIONMARK_SPACE=' ? ';
	public static final String UNDERSCORE_PERCENTAGE='_%';
	public static final String DOLLAR_SPACE='$ ';
	public static final String HYPHEN_DOLALR='-$';
	public static final String HYPHEN_DOLLAR_SPACE='-$ ';
	public static final String PERCENT_PIPE_SPACE='% | ';
	public static final String STATIC_SELECT='Select';
	public static final String STATICO='O';
	public static final String AMPERSAND='&';
	public static final String BACK_SLASH2_DOT='\\.';
	public static final String BLANK=' ';
	public static final String CLOSE_BRACE='}';
	public static final String CLOSEBRACKET=')';
	public static final String COLON=':';
	public static final String COMMA_SPACE=', ';
	public static final String COMMA=',';
	public static final String CONCAT='';
	public static final String DOT_DOLLAR_ESCPAED='\\.$';
	public static final String DOT='.';
	public static final String DOUBLE_QOUTE='"';
	public static final String DOUBLE_TILDE='~~';
	public static final String DOUBLETABSPACE='   ';
	public static final String EQUAL='=';
	public static final String FALSE_CAMEL_LITERAL='False';
	public static final String FALSE_LITERAL='false';
	public static final String HASH='#';
	public static final String HYPHEN='-';
	public static final String OPEN_BRACE_FLOWER='{';
	public static final String OPEN_BRACE='(';
	public static final String PERCENTAGE='%';
	public static final String SEMI_COLON=';';
	public static final String SLASH='/';
	public static final String SPACECOMA=' ,';
	public static final String SPACE_COLON_SPACE=' : ';
	public static final String STATIC_CAMEL_LITERAL='Static';
	public static final String TABSPACE='  ';
	public static final String TRUE_CAMEL_LITERAL='True';
	public static final String TRUE_CAPS_LITERAL='TRUE';
	public static final String TRUE_LITERAL='true';
	public static final String UNDERSCORE='_';
	public static final String ATTHERATE='@';
	public static final String STATIC_STRING='String';
	public static final String STATIC_UPDATE='update';
	public static final String SPACE_OPENSQUAREBRACKET = ' [';
	public static final String PERCENT_SPACE_PIPE = '% |';
	public static final String DOUBLE_QUOTES_DOT = '".';
	public static final String SIVAR_CONST_00 = '0.0';
}