@charset "UTF-8";

/*=================================================================
AT&T Partner Exchange Customized Stylesheet ---------------------------
==================================================== */

/* Akhil 7/29/16: hero style customized updates */

ol,ul,li{ 
    list-style: none; 
    margin: 0; 
} 

/* Robyn 8/16/16: removed important declaration to fix spacing on old product/grow pages for the h3 heading */ 
h1, 
h2, 
h3, 
h4, 
h5, 
h6 { 
    margin: 0; 
}